### ISSUE TITLE
error pas buka list-rak.php

### ISSUE THREAD

**Issue by pirey** [YusufAdiNugroho1/perpus#1]
![image](https://user-images.githubusercontent.com/10344542/71704185-52fc3600-2e0b-11ea-9538-c40c5d547a5a.png)
@YusufAdiNugroho1

**Comment by pirey** [comment]
@YusufAdiNugroho1 coba kamu periksa error kenapa, trs dibenahi, trs dipush lagi.

**Comment by YusufAdiNugroho1** [comment]
Iya mas
Pada tanggal 3 Jan 2020 09.29, "Yeri Pratama" <notifications@github.com>
menulis:

**Comment by YusufAdiNugroho1** [comment]
![ss](https://user-images.githubusercontent.com/56142220/71705387-17189f00-2e12-11ea-86ac-411e4551f358.PNG)

**Comment by YusufAdiNugroho1** [comment]
bisa itu mas

**Comment by pirey** [comment]
punyaku blm bisa, coba kamu clone project ini di komputer lain, lalu coba jalankan, bisa gak

**Comment by YusufAdiNugroho1** [comment]
Saya Coba di netbook-nya Agung bisa itu mas

Pada tanggal 10 Jan 2020 18.28, "Yeri Pratama" <notifications@github.com>
menulis:
